### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by bibb** [gymreklab/STRTools#20]
Hello, 

I'm trying to run plinkSTR in my ubuntu system and I keep getting this problem:

File "/usr/local/lib/python3.6/dist-packages/strtools-1.0.0-py3.6.egg/plinkSTR/plinkSTR.py", line 48
    print record.start, int(start), record.ID
                      ^
SyntaxError: invalid syntax

I run dumpSTR and the other tools from STRtools perfectly fine.

Thanks

Bernabe

ps: Could you please provide an example dataset to see if the problem is with my data? I would appreciate that!.

**Comment by nmmsv** [comment]
We've made some changes, and they should fix this issue (we had a python 3 compatibility problem).
Please let me know if you face any other issues.
