### ISSUE TITLE
Install help for others

### ISSUE THREAD

**Issue by Phillip-a-richmond** [gymreklab/STRTools#21]
Not sure if this is much use, but I am eager to use the toolkit and am using it on a shared system where I don't have root privileges. With virtualenv, installing this toolkit is trivial. 

Just a few extra commands on top of your existing install instructions can get this working on a shared system where the user has limited privileges:

Create virtualenv on  system, then installing the toolkit:
### My python loading from module system
```module load python/3.7```

### Run virutalenv to create an environment, here I do it within a directory called ~/TOOLS/
```virtualenv --no-download ~/TOOLS/STR_Tools_Environment```
### Activate your environment
```source ~/TOOLS/STR_Tools_Environment/bin/activate```
### install scipy dependency
```pip install scipy```

### Clone this repo
```cd ~/TOOLS/```
```git clone https://github.com/gymreklab/STRTools```
```cd STRTools```

### Run your set-up
```python setup.py --install --prefix=~/project/TOOLS/STR_Tools_Environment/```

> And Voila! you're done!

### Using it
```source ~/project/TOOLS/STR_Tools_Environment/bin/activate```
```dumpSTR -h```

**Comment by bibb** [comment]
Hi, thanks for the instructions, but I'm still unable to run plinkSTR, I have tried many ways to install it and make it run but I always have the same error:

plinkSTR -h

Traceback (most recent call last):
  File "/Users/bib0660/TOOLS/STR_Tools_Environment/bin/plinkSTR", line 11, in <module>
    load_entry_point('strtools==1.0.0', 'console_scripts', 'plinkSTR')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/bib0660/TOOLS/STRTools/plinkSTR/plinkSTR.py", line 48
    print record.start, int(start), record.ID
               ^
SyntaxError: invalid syntax

It looks like this is a coding mistake, isn't it? Unfortunately I haven't received any help from the developers in orrder to fix this

Thanks

**Comment by nmmsv** [comment]
Hi @bibb 
I believe plinkSTR only runs in python2.7 environments. Can you please confirm this @shubhamsaini ?

@Phillip-a-richmond thanks for detailed instructions!

**Comment by nmmsv** [comment]
I made some changes that should fix the plinkSTR issue. Thanks for reporting it!
